enum ActionTypes {
  UPDATE_PROFILE = 'CLIENT_UI/PROFILE_MANAGEMENT/UPDATE_PROFILE',
  UPDATE_PROFILE_SUCCESS = 'CLIENT_UI/PROFILE_MANAGEMENT/UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILED = 'CLIENT_UI/PROFILE_MANAGEMENT/UPDATE_PROFILE_FAILED',

  UPDATE_PROFILE_IMAGE = 'CLIENT_UI/PROFILE_MANAGEMENT/UPDATE_PROFILE_IMAGE',
  UPDATE_PROFILE_IMAGE_SUCCESS = 'CLIENT_UI/PROFILE_MANAGEMENT/UPDATE_PROFILE_IMAGE_SUCCESS',
  UPDATE_PROFILE_IMAGE_FAILED = 'CLIENT_UI/PROFILE_MANAGEMENT/UPDATE_PROFILE_IMAGE_FAILED',

  GET_ACTIVITY_STATUS_LIST = 'CLIENT_UI/PROFILE_MANAGEMENT/GET_ACTIVITY_STATUS_LIST',
  GET_ACTIVITY_STATUS_LIST_SUCCESS = 'CLIENT_UI/PROFILE_MANAGEMENT/GET_ACTIVITY_STATUS_LIST_SUCCESS',
  GET_ACTIVITY_STATUS_LIST_FAILED = 'CLIENT_UI/PROFILE_MANAGEMENT/GET_ACTIVITY_STATUS_LIST_FAILED',

  GET_RESTAURANT_LIST = 'CLIENT_UI/PROFILE_MANAGEMENT/GET_RESTAURANT_LIST',
  GET_RESTAURANT_LIST_SUCCESS = 'CLIENT_UI/PROFILE_MANAGEMENT/GET_RESTAURANT_LIST_SUCCESS',
  GET_RESTAURANT_LIST_FAILED = 'CLIENT_UI/PROFILE_MANAGEMENT/GET_RESTAURANT_LIST_FAILED',

  RESET_REDUX = 'CLIENT_UI/PROFILE_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
