enum ActionTypes {
  GET_RESTAURANT_LIST = 'CLIENT_UI/RESTAURANT_MANAGEMENT/GET_RESTAURANT_LIST',
  GET_RESTAURANT_LIST_SUCCESS = 'CLIENT_UI/RESTAURANT_MANAGEMENT/GET_RESTAURANT_LIST_SUCCESS',
  GET_RESTAURANT_LIST_FAILED = 'CLIENT_UI/RESTAURANT_MANAGEMENT/GET_RESTAURANT_LIST_FAILED',

  GET_RESTAURANT = 'CLIENT_UI/RESTAURANT_MANAGEMENT/GET_RESTAURANT',
  GET_RESTAURANT_SUCCESS = 'CLIENT_UI/RESTAURANT_MANAGEMENT/GET_RESTAURANT_SUCCESS',
  GET_RESTAURANT_FAILED = 'CLIENT_UI/RESTAURANT_MANAGEMENT/GET_RESTAURANT_FAILED',

  GET_ACTIVITY_LIST = 'CLIENT_UI/RESTAURANT_MANAGEMENT/GET_ACTIVITY_LIST',
  GET_ACTIVITY_LIST_SUCCESS = 'CLIENT_UI/RESTAURANT_MANAGEMENT/GET_ACTIVITY_LIST_SUCCESS',
  GET_ACTIVITY_LIST_FAILED = 'CLIENT_UI/RESTAURANT_MANAGEMENT/GET_ACTIVITY_LIST_FAILED',

  RESET_REDUX = 'CLIENT_UI/RESTAURANT_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
