enum ActionTypes {
  GET_ACTIVITY_LIST = 'CLIENT_UI/ACTIVITY_MANAGEMENT/GET_ACTIVITY_LIST',
  GET_ACTIVITY_LIST_SUCCESS = 'CLIENT_UI/ACTIVITY_MANAGEMENT/GET_ACTIVITY_LIST_SUCCESS',
  GET_ACTIVITY_LIST_FAILED = 'CLIENT_UI/ACTIVITY_MANAGEMENT/GET_ACTIVITY_LIST_FAILED',

  GET_RESTAURANT_LIST = 'CLIENT_UI/ACTIVITY_MANAGEMENT/GET_RESTAURANT_LIST',
  GET_RESTAURANT_LIST_SUCCESS = 'CLIENT_UI/ACTIVITY_MANAGEMENT/GET_RESTAURANT_LIST_SUCCESS',
  GET_RESTAURANT_LIST_FAILED = 'CLIENT_UI/ACTIVITY_MANAGEMENT/GET_RESTAURANT_LIST_FAILED',

  GET_ACTIVITY = 'CLIENT_UI/ACTIVITY_MANAGEMENT/GET_ACTIVITY',
  GET_ACTIVITY_SUCCESS = 'CLIENT_UI/ACTIVITY_MANAGEMENT/GET_ACTIVITY_SUCCESS',
  GET_ACTIVITY_FAILED = 'CLIENT_UI/ACTIVITY_MANAGEMENT/GET_ACTIVITY_FAILED',

  STAMP_PASSPORT = 'CLIENT_UI/ACTIVITY_MANAGEMENT/STAMP_PASSPORT',
  STAMP_PASSPORT_SUCCESS = 'CLIENT_UI/ACTIVITY_MANAGEMENT/STAMP_PASSPORT_SUCCESS',
  STAMP_PASSPORT_FAILED = 'CLIENT_UI/ACTIVITY_MANAGEMENT/STAMP_PASSPORT_FAILED',

  RESET_REDUX = 'CLIENT_UI/ACTIVITY_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
