enum ActionTypes {
  REGISTER_USER = 'CLIENT_UI/AUTH_MANAGEMENT/REGISTER_USER',
  REGISTER_USER_SUCCESS = 'CLIENT_UI/AUTH_MANAGEMENT/REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILED = 'CLIENT_UI/AUTH_MANAGEMENT/REGISTER_USER_FAILED',

  EMAIL_VERIFICATION = 'CLIENT_UI/AUTH_MANAGEMENT/EMAIL_VERIFICATION',
  EMAIL_VERIFICATION_SUCCESS = 'CLIENT_UI/AUTH_MANAGEMENT/EMAIL_VERIFICATION_SUCCESS',
  EMAIL_VERIFICATION_FAILED = 'CLIENT_UI/AUTH_MANAGEMENT/EMAIL_VERIFICATION_FAILED',

  LOGIN = 'CLIENT_UI/AUTH_MANAGEMENT/LOGIN',
  LOGIN_SUCCESS = 'CLIENT_UI/AUTH_MANAGEMENT/LOGIN_SUCCESS',
  LOGIN_FAILED = 'CLIENT_UI/AUTH_MANAGEMENT/LOGIN_FAILED',

  FORGOT_LOGIN_PASSWORD = 'CLIENT_UI/AUTH_MANAGEMENT/FORGOT_LOGIN_PASSWORD',
  FORGOT_LOGIN_PASSWORD_SUCCESS = 'CLIENT_UI/AUTH_MANAGEMENT/FORGOT_LOGIN_PASSWORD_SUCCESS',
  FORGOT_LOGIN_PASSWORD_FAILED = 'CLIENT_UI/AUTH_MANAGEMENT/FORGOT_LOGIN_PASSWORD_FAILED',

  FORGOT_LOGIN_PASSWORD_LINK_VERIFY = 'CLIENT_UI/AUTH_MANAGEMENT/FORGOT_LOGIN_PASSWORD_LINK_VERIFY',
  FORGOT_LOGIN_PASSWORD_LINK_VERIFY_SUCCESS = 'CLIENT_UI/AUTH_MANAGEMENT/FORGOT_LOGIN_PASSWORD_LINK_VERIFY_SUCCESS',
  FORGOT_LOGIN_PASSWORD_LINK_VERIFY_FAILED = 'CLIENT_UI/AUTH_MANAGEMENT/FORGOT_LOGIN_PASSWORD_LINK_VERIFY_FAILED',

  RESET_USER_PASSWORD = 'CLIENT_UI/AUTH_MANAGEMENT/RESET_USER_PASSWORD',
  RESET_USER_PASSWORD_SUCCESS = 'CLIENT_UI/AUTH_MANAGEMENT/RESET_USER_PASSWORD_SUCCESS',
  RESET_USER_PASSWORD_FAILED = 'CLIENT_UI/AUTH_MANAGEMENT/RESET_USER_PASSWORD_FAILED',

  RESET_REDUX = 'CLIENT_UI/AUTH_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
